/* Cópia de RESERVA do catálogo (sis_produtos, 29/09/2026, fotos no Drive), usada só se o Firestore não responder.
   O site lê o catálogo de verdade em js/catalogo.js. */
window.DLUH_CATALOGO = {
 "produtos": [
  {
   "id": "coda-i-lWgOCiAYMR",
   "nome": "4 Queijos",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Queijo, mussarela, queijo Minas, queijo ricota.",
   "imagem": "https://lh3.googleusercontent.com/d/1rOE4hapejE2koaWwLx8n6g_lG9ak65k6",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-Chsz_wZyaS",
   "nome": "Arrepiadinho de frango com bacon",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Frango, bacon picado.",
   "imagem": "https://lh3.googleusercontent.com/d/1QuvSD4mW9A5Qj2e3TFTK2SGYwRFDFbKP",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-PRJRnET_3B",
   "nome": "Assado Pronto Congelado 25x",
   "categoria": "Pacote Congelado",
   "valorUnit": 2200,
   "qtdMin": 1,
   "descricao": "25 Unidades em cada pacote!",
   "imagem": "https://lh3.googleusercontent.com/d/1sWERjuFXVqh7SKnBm-6A3DYOQy9Ly2Gh",
   "destaque": false,
   "tiposPacote": [
    "Assado"
   ]
  },
  {
   "id": "coda-i-IrMNozUsqQ",
   "nome": "Assado Pronto Congelado 50x",
   "categoria": "Pacote Congelado",
   "valorUnit": 4200,
   "qtdMin": 1,
   "descricao": "50 Unidades em cada pacote!",
   "imagem": "https://lh3.googleusercontent.com/d/1NUDSDp54mdmoVEBlaTsqwmdYLvLwvhuN",
   "destaque": false,
   "tiposPacote": [
    "Assado"
   ]
  },
  {
   "id": "coda-i-LxFtiRie82",
   "nome": "Barquete",
   "categoria": "Salgado Especial",
   "valorUnit": 90,
   "qtdMin": 50,
   "descricao": "Casquinha com recheio de salpicão.",
   "imagem": "https://lh3.googleusercontent.com/d/1OU9_L4rNn1YG6CDeXHZCplzQc74eo9dD",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-QbRuUqovzI",
   "nome": "Beijinho",
   "categoria": "Doce",
   "valorUnit": 130,
   "qtdMin": 50,
   "descricao": "Leite condensado e coco ralado.",
   "imagem": "https://lh3.googleusercontent.com/d/1JqpHVT0buT1L-IXFrvxSqPaDHCYIGZT7",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-fa1ef1T-S-",
   "nome": "Bolinha Crocante de Mussarela e Orégano",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Mussarela e oregano empanado na farinha panko.",
   "imagem": "https://lh3.googleusercontent.com/d/1epncjxDOHKi32qdalTiImm8dDMC99P8G",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-liVdAfgbL1",
   "nome": "Bolinha Romeu e Julieta",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Queijo com goiabada, polvilhado com açúcar e canela.",
   "imagem": "https://lh3.googleusercontent.com/d/1ERggmPCV0mTime8dIog-6gFv8zEcUz5C",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-U66yJOr9yl",
   "nome": "Bolo de Cenoura com Calda",
   "categoria": "Bolo",
   "valorUnit": 2800,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "https://lh3.googleusercontent.com/d/1EHwsiR7U68KRapXxbhq5yqM5gPaY1TR7",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-VS5R4tdQKE",
   "nome": "Bolo de Chocolate",
   "categoria": "Bolo",
   "valorUnit": 2800,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "https://lh3.googleusercontent.com/d/18PEyw7LmbhL_LYnS0lMl1ZwQhqshr3RJ",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-DrUFqSeJju",
   "nome": "Bolo de Coco",
   "categoria": "Bolo",
   "valorUnit": 1700,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "https://lh3.googleusercontent.com/d/1ZwNWnoAD0LUm5F5E63LZMhmSfiHloHlC",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-0D0jMIH19o",
   "nome": "Bolo de Fubá",
   "categoria": "Bolo",
   "valorUnit": 1700,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "https://lh3.googleusercontent.com/d/1FDZrJsU8Im7Bv4aesR7y5XDGdt_P10u8",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-doDKIB4BCc",
   "nome": "Bolo de Limão com Calda",
   "categoria": "Bolo",
   "valorUnit": 2800,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "https://lh3.googleusercontent.com/d/16tk6qnQ13Xs5JrdCFx-bsAmq6-DTvAij",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-kPwk_DLqaW",
   "nome": "Bolo Mesclado",
   "categoria": "Bolo",
   "valorUnit": 1700,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "https://lh3.googleusercontent.com/d/1vcj4bd3rOU3XeT4sxHndUXM7hOfHW_j5",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-yGJLSMS0Lg",
   "nome": "Bolo Vulcão",
   "categoria": "Bolo",
   "valorUnit": 3500,
   "qtdMin": 1,
   "descricao": "Brigadeiro, Ninho com Brigadeiro, Limão e Cenoura.",
   "imagem": "https://lh3.googleusercontent.com/d/12vGDmaSWa_UPbQN_PwpYIrQDa43jzxTa",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-gCSMZKKODl",
   "nome": "Bombom de calabresa com presunto (Com passas)",
   "categoria": "Assado",
   "valorUnit": 80,
   "qtdMin": 25,
   "descricao": "Calabresa, presunto e passas",
   "imagem": "https://lh3.googleusercontent.com/d/1DL9V_xQOgfunOHG6p3O3Eclqqq97DPhN",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-WjINxAvF8p",
   "nome": "Brigadeiro",
   "categoria": "Doce",
   "valorUnit": 130,
   "qtdMin": 50,
   "descricao": "Leite condensado e cacau 50%.",
   "imagem": "https://lh3.googleusercontent.com/d/1_onlkECHuSZTXlAlxHDRwlXc-OEIrq1j",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-AVTm5gknpI",
   "nome": "Brigadeiro Gourmet",
   "categoria": "Doce Goumert",
   "valorUnit": 160,
   "qtdMin": 50,
   "descricao": "Leite condensado, cacau 50% e pedacinhos de chocolate ao leite",
   "imagem": "https://lh3.googleusercontent.com/d/1j3bcQ-aAmw_RB9od5safKjQtnfpe6Dpi",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-GUQA08sAAf",
   "nome": "Cachorro Quente",
   "categoria": "Lanches",
   "valorUnit": 180,
   "qtdMin": 25,
   "descricao": "Combinado",
   "imagem": "https://lh3.googleusercontent.com/d/1iKMMwHLmQROIQx5_cdXEm8Bi6QNpDa1e",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-qDpALEKVUQ",
   "nome": "Cajuzinho",
   "categoria": "Doce",
   "valorUnit": 130,
   "qtdMin": 50,
   "descricao": "Leite condensado, amendoim triturado e cacau 50%.",
   "imagem": "https://lh3.googleusercontent.com/d/1EmS1-gKOomh3aA1LVwXa-EI3R9NtbRdd",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-63AUoJaY2Z",
   "nome": "Carne seca",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Carne desfiada",
   "imagem": "https://lh3.googleusercontent.com/d/1RbcGrW0NGXl7F2eO6NEGntMJY7v65OMc",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-UfERdrXVvT",
   "nome": "Casadinho",
   "categoria": "Doce",
   "valorUnit": 130,
   "qtdMin": 50,
   "descricao": "brigadeiro de ninho e meio brigadeiro de chocolate.",
   "imagem": "https://lh3.googleusercontent.com/d/1YgBy6DFrQfaCBNEy-8YR6zFpn2emRsu3",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-p67BO9CRW1",
   "nome": "Charutinho de frango com bacon",
   "categoria": "Assado",
   "valorUnit": 80,
   "qtdMin": 25,
   "descricao": "Frango, requeijão cremoso e bacon.",
   "imagem": "https://lh3.googleusercontent.com/d/1A2E6OPDliIgoIb_0z4pYVbLF4bVOWW41",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-OHU7mfpMq8",
   "nome": "Churros",
   "categoria": "Doce Goumert",
   "valorUnit": 160,
   "qtdMin": 50,
   "descricao": "Leite condensado, doce de leite e toque leve de canela.",
   "imagem": "https://lh3.googleusercontent.com/d/1eTtrqfSXHHgZ-AEvLjVn4HMe_PE2YTNw",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-DRZonYqzLG",
   "nome": "Coxinha",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Frango desfiado.",
   "imagem": "https://lh3.googleusercontent.com/d/1QPEusYtpkcgNDXgLQkrNHYXTeZ3n0DFs",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-sA5zJjaqBc",
   "nome": "Crispim de milho e queijo",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Massa de creme de  milho com recheio de mussarela e milho.",
   "imagem": "https://lh3.googleusercontent.com/d/1hwmKucQco4gUMxtCceBmf0B2HYiadPdl",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-n7A3X0VxiF",
   "nome": "Croquete",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Massa de salgado cozido com carne desfiado, com leve toque apimentado.",
   "imagem": "https://lh3.googleusercontent.com/d/1pSBRBA9Y7eP9TUS3WmwylJkoMHKvZAdI",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-SYcjriE6l7",
   "nome": "Empada",
   "categoria": "Assado",
   "valorUnit": 80,
   "qtdMin": 25,
   "descricao": "Frango com azeitona picada.",
   "imagem": "https://lh3.googleusercontent.com/d/1f7hjviPx_5slwf4UK4YpijoSgsZa5k2Y",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-NP70V1BjfJ",
   "nome": "Empadão de Frango Grande",
   "categoria": "Assado",
   "valorUnit": 12000,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-UK_XyRdKzu",
   "nome": "Empadão de Frango Médio",
   "categoria": "Assado",
   "valorUnit": 8500,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-MsPD-P_b0G",
   "nome": "Empadão de Frango Pequeno",
   "categoria": "Assado",
   "valorUnit": 6000,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-hHe00kE_wK",
   "nome": "Empanadinho de frango",
   "categoria": "Salgado Especial",
   "valorUnit": 90,
   "qtdMin": 50,
   "descricao": "Pedaços de frango empanado no palito",
   "imagem": "https://lh3.googleusercontent.com/d/1Jst5T46rfyBDk2TprtFms5kV3_9rSY2W",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-1FgGxQfVy3",
   "nome": "Espetinho de Provolone",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Mussarela e provolone.",
   "imagem": "https://lh3.googleusercontent.com/d/1W7K33r47igcDRoufIrS2Yvm93YQwVELY",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-sUu3BpK4WW",
   "nome": "Ferrero Rocher",
   "categoria": "Doce Goumert",
   "valorUnit": 160,
   "qtdMin": 50,
   "descricao": "Brigadeiro ao leite com pedaços de avelã e uma pitanga de nutela.",
   "imagem": "https://lh3.googleusercontent.com/d/1ydNhEioftt2VuA45stGdSsY1m_yiS9n0",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-qlDs8dEsL4",
   "nome": "Kibe",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Massa de kibe e carne moida.",
   "imagem": "https://lh3.googleusercontent.com/d/1zlRtC-p0guFZTf2kQ67qsjhCfVWERfv9",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-6gN8KarTCs",
   "nome": "Kit Família",
   "categoria": "Kit",
   "valorUnit": 22000,
   "qtdMin": 1,
   "descricao": "80 Salgados\n30 Docinhos\n1 Bolo 1Kg\n10 Mini Hamburgueres\n10 Mini Pizzas",
   "imagem": "",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-4wxd02rGKL",
   "nome": "Leite em pó",
   "categoria": "Doce",
   "valorUnit": 130,
   "qtdMin": 50,
   "descricao": "Leite em pó e leite de côco.",
   "imagem": "https://lh3.googleusercontent.com/d/1J_RNK8Tp5JxIcS_1Yl-NzJaEbbRmgUg8",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-DJPIPQX4fI",
   "nome": "Maracuja",
   "categoria": "Doce",
   "valorUnit": 130,
   "qtdMin": 50,
   "descricao": "Leite condensado com geleia de maracujá.",
   "imagem": "https://lh3.googleusercontent.com/d/15okBwLlKJixyGcBDWxHuXY1a4KrbrgBv",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-vXOYueK3II",
   "nome": "Mini Hambúrguer",
   "categoria": "Lanches",
   "valorUnit": 220,
   "qtdMin": 25,
   "descricao": "",
   "imagem": "https://lh3.googleusercontent.com/d/1swAVd-xp5urrG2c5-2JxKP91m9yAHk5f",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-jSkGfNyQe_",
   "nome": "Mini Pizza",
   "categoria": "Lanches",
   "valorUnit": 150,
   "qtdMin": 25,
   "descricao": "Mussarela e presunto ou Frango desfiado com mussarela e milho",
   "imagem": "https://lh3.googleusercontent.com/d/1KQpPzofmkBRTFXYQ62-uF0GGJ4fWyTy3",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-rz0udi8xVW",
   "nome": "Napolitano",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Mussarela, presunto e oregano.",
   "imagem": "https://lh3.googleusercontent.com/d/1WsSllupBBHmnMj3K_mHLv4AtBCU5gnr-",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-_mI5LsBu2L",
   "nome": "Ninho com Nutella",
   "categoria": "Doce Goumert",
   "valorUnit": 160,
   "qtdMin": 50,
   "descricao": "Brigadeiro de ninho com uma pitanga de nutela.",
   "imagem": "https://lh3.googleusercontent.com/d/1zVbaHXAIoogNcsL8pL6D_5rBfjcoafv3",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-HXSfIh9C7E",
   "nome": "Olho de Sogra",
   "categoria": "Doce",
   "valorUnit": 160,
   "qtdMin": 50,
   "descricao": "",
   "imagem": "",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-etssEG3b3J",
   "nome": "Oreo",
   "categoria": "Doce Goumert",
   "valorUnit": 160,
   "qtdMin": 50,
   "descricao": "Brigadeiro branco com pedaços de bolacha oreo.",
   "imagem": "https://lh3.googleusercontent.com/d/12DrOdzbHirAGHe9r45pN2t-UKtpzyHf7",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-Ra5zmgegYX",
   "nome": "Pastel de calabresa",
   "categoria": "Assado",
   "valorUnit": 80,
   "qtdMin": 25,
   "descricao": "Calabresa Triturada.",
   "imagem": "https://lh3.googleusercontent.com/d/1VeFeCnbyEExrrToPv6gq5T42hpgQK1uw",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-boHO-ZzasI",
   "nome": "Pastel frango",
   "categoria": "Assado",
   "valorUnit": 80,
   "qtdMin": 25,
   "descricao": "Frango desfiado com requeijão cremoso",
   "imagem": "https://lh3.googleusercontent.com/d/1xIwiLkohYSw4O8-rovWnRgbsnlFnqdLi",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "cTwetBFa47SO5DJBw16O",
   "nome": "Pastel Pipoca",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "",
   "imagem": "",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i--bb8hj1lJ-",
   "nome": "Pastel pipoca de carne moida",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Massa pipocada de carne moida.",
   "imagem": "https://lh3.googleusercontent.com/d/15AysaIlIHzlql_p8eZiL06U8OvcoXAP-",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-48cXKOrtm8",
   "nome": "Pastel Pipoca de Frango",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "",
   "imagem": "",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-_6Yojcz9oY",
   "nome": "Pastel pipoca de Queijo",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Massa pipocada com queijo mussarela",
   "imagem": "https://lh3.googleusercontent.com/d/1C5geRQzPU5xpLf43bE-SKStz3GelhSHu",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-8Eh-kzDZ1V",
   "nome": "Pastel pipoca Napolitano",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Massa pipocada com Mussarela, presunto e oregano.",
   "imagem": "https://lh3.googleusercontent.com/d/130t_1Do6kTpq_44ywRMmVTdvt5a6Ki-D",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-65cKBE5_4I",
   "nome": "Pastel Romeu e Julieta",
   "categoria": "Assado",
   "valorUnit": 80,
   "qtdMin": 25,
   "descricao": "Queijo e goiabada",
   "imagem": "https://lh3.googleusercontent.com/d/1AJx4YGZE9DDhHx9WcqPLU9_lr4Km78o3",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-cZoQldspw8",
   "nome": "Paçoca",
   "categoria": "Doce Goumert",
   "valorUnit": 160,
   "qtdMin": 50,
   "descricao": "Brigadeiro de paçoca",
   "imagem": "https://lh3.googleusercontent.com/d/1rAfnTTj7hPRYfJNaoU7ln54mFL5-e1Cw",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-1Po2h-j8oc",
   "nome": "Quiche de alho poró e tomate seco",
   "categoria": "Salgado Especial",
   "valorUnit": 90,
   "qtdMin": 50,
   "descricao": "Mistura de queijos com tomate seco picado.",
   "imagem": "https://lh3.googleusercontent.com/d/15On7LTII86psB1c_M8fm2VPnvd5IkALT",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-W36qnpYJBg",
   "nome": "Quiches de Queijo",
   "categoria": "Salgado Especial",
   "valorUnit": 90,
   "qtdMin": 50,
   "descricao": "Mistura de queijos com alho poró picado.",
   "imagem": "https://lh3.googleusercontent.com/d/1a8S1AXvRWXnKk6DtxF4xOroFIbbHb2JN",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-4dpUrmg96a",
   "nome": "Romeu e Julieta",
   "categoria": "Doce Goumert",
   "valorUnit": 160,
   "qtdMin": 50,
   "descricao": "Brigadeiro de queijo com goiabada.",
   "imagem": "https://lh3.googleusercontent.com/d/1Cs5bsV0mMa9rivZngX81OdygXwbj4l9J",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-oN2tTpAzvB",
   "nome": "Salgado Pronto Congelado 25x",
   "categoria": "Pacote Congelado",
   "valorUnit": 2000,
   "qtdMin": 1,
   "descricao": "25 Unidades em cada pacote!",
   "imagem": "https://lh3.googleusercontent.com/d/1lsOxLHOmccWph71WzjWi34BIrPBs9wpr",
   "destaque": false,
   "tiposPacote": [
    "Salgado Frito"
   ]
  },
  {
   "id": "coda-i-jB4I4g4AF_",
   "nome": "Salgado Pronto Congelado 50x",
   "categoria": "Pacote Congelado",
   "valorUnit": 4000,
   "qtdMin": 1,
   "descricao": "50 Unidades em cada pacote!",
   "imagem": "https://lh3.googleusercontent.com/d/1ZjSVUfpRa6WJll5QfWRW0GOlrneI8efj",
   "destaque": false,
   "tiposPacote": [
    "Salgado Frito"
   ]
  },
  {
   "id": "coda-i-i41qCOpcKT",
   "nome": "Sanduiche Natural",
   "categoria": "Lanches",
   "valorUnit": 180,
   "qtdMin": 25,
   "descricao": "Combinado",
   "imagem": "https://lh3.googleusercontent.com/d/1eiN_tHT5m8vphTqywf8-yTLgtjbqBZ8g",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-6-KxXPSl1p",
   "nome": "Tartalete de ovo de codorna",
   "categoria": "Salgado Especial",
   "valorUnit": 90,
   "qtdMin": 50,
   "descricao": "Molho rose e ovo de codorna.",
   "imagem": "https://lh3.googleusercontent.com/d/1JRg4fZ-0nwmBIEXy-Ow7CDsP7NdYJhdO",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-SryrecbPW1",
   "nome": "Test",
   "categoria": "Bolo",
   "valorUnit": 200,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-Wk_qb5tnWm",
   "nome": "Torta Grande",
   "categoria": "Assado",
   "valorUnit": 10000,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "https://lh3.googleusercontent.com/d/1SHU8zZq93rfSLzWWxvRFBmA8YjsLVYec",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-Z-JCqRuQbF",
   "nome": "Torta Média",
   "categoria": "Assado",
   "valorUnit": 7000,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "https://lh3.googleusercontent.com/d/1PegGFX8xy-eP7ElNXI8N2JWBX56_oi8Y",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-Tq3P_g__Ii",
   "nome": "Torta Pequena",
   "categoria": "Assado",
   "valorUnit": 5000,
   "qtdMin": 1,
   "descricao": "",
   "imagem": "https://lh3.googleusercontent.com/d/15t70K9BoqLN6YHrZFjbYXaFA01jVTYWK",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-euW01OIVP1",
   "nome": "Tortinha de frango com Bacon",
   "categoria": "Assado",
   "valorUnit": 80,
   "qtdMin": 25,
   "descricao": "Frango desfiado com bacon picado.",
   "imagem": "https://lh3.googleusercontent.com/d/1ZkKxTQpxWK_mJ6jPHYxTQWaLV24HBB3A",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-7DsVWbUkP_",
   "nome": "Tortinha de frango com catupiry",
   "categoria": "Assado",
   "valorUnit": 80,
   "qtdMin": 25,
   "descricao": "Frango e catupiry.",
   "imagem": "https://lh3.googleusercontent.com/d/1RChiiWEUPaYJp1OToJTe9fnrx3EoPng9",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-_uSABQN-1I",
   "nome": "Tortinha de palmito",
   "categoria": "Assado",
   "valorUnit": 80,
   "qtdMin": 25,
   "descricao": "",
   "imagem": "https://lh3.googleusercontent.com/d/15KTe7x3WPE3FLchfMIaaSh4zax95ejdn",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-niIqS8OGTE",
   "nome": "Travesseirinho de carne moida",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Carne Moida saborosa.",
   "imagem": "https://lh3.googleusercontent.com/d/1OrBQhLsc6yXXXrGKnDhcyJwIHft69Odv",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-NzSurQgdNG",
   "nome": "Travesseirinho de creme de milho",
   "categoria": "Salgado Frito",
   "valorUnit": 75,
   "qtdMin": 25,
   "descricao": "Creme de milho e queijo.",
   "imagem": "https://lh3.googleusercontent.com/d/1VAl-8Iw4Mg7-aAKqH-Niy4fPVSkEnZcJ",
   "destaque": true,
   "tiposPacote": []
  },
  {
   "id": "coda-i-qHef9o3ywG",
   "nome": "Trouxinha de lombo canadense e abacaxi",
   "categoria": "Salgado Especial",
   "valorUnit": 90,
   "qtdMin": 50,
   "descricao": "Lombo canadense com pedaços de abacaxi picado.",
   "imagem": "",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-nl4PLHEp1j",
   "nome": "🍰Bolo aro 13",
   "categoria": "Bolo",
   "valorUnit": 9000,
   "qtdMin": 1,
   "descricao": "Serve de 8 a 10 pessoas!",
   "imagem": "https://lh3.googleusercontent.com/d/10ydHMet8zR8TrlYgQ6tOwCNHTC_oqqzc",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-osmdHLIKmn",
   "nome": "🍰Bolo aro 15",
   "categoria": "Bolo",
   "valorUnit": 11000,
   "qtdMin": 1,
   "descricao": "Serve de 10 a 15 pessoas!",
   "imagem": "https://lh3.googleusercontent.com/d/16Uy-_s8JV08OU089-NXP5Ilg2RlFuQAL",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-dhgNry5usN",
   "nome": "🍰Bolo aro 18",
   "categoria": "Bolo",
   "valorUnit": 14000,
   "qtdMin": 1,
   "descricao": "Serve de 15 a 20 pessoas!",
   "imagem": "https://lh3.googleusercontent.com/d/1d8vTyCzvCDJuSRai82Xo29VLPxKjvujZ",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-pQ0AD_iitm",
   "nome": "🍰Bolo aro 20",
   "categoria": "Bolo",
   "valorUnit": 18000,
   "qtdMin": 1,
   "descricao": "Serve de 20 a 30 pessoas!",
   "imagem": "https://lh3.googleusercontent.com/d/1BB-7THIHKBPPXeRyRaUqodwe5YsHEKxu",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-vCwLrq4jOk",
   "nome": "🍰Bolo aro 25",
   "categoria": "Bolo",
   "valorUnit": 25000,
   "qtdMin": 1,
   "descricao": "Serve de 25 a 30 pessoas!",
   "imagem": "https://lh3.googleusercontent.com/d/1oCyJJV_gXOosFEka6TNlufrARkPjGw0l",
   "destaque": false,
   "tiposPacote": []
  },
  {
   "id": "coda-i-4n-zr2Gb5a",
   "nome": "🍰Bolo aro 30",
   "categoria": "Bolo",
   "valorUnit": 32000,
   "qtdMin": 1,
   "descricao": "Serve de 45 a 50 pessoas!",
   "imagem": "https://lh3.googleusercontent.com/d/1T305s05yIKt4Coqe1KUnf-l4AgL224QP",
   "destaque": false,
   "tiposPacote": []
  }
 ],
 "recheios": [
  "Creme Ninho",
  "Chocolate",
  "4 Leites",
  "Brigadeiro de Ninho",
  "Brigadeiro",
  "Creme Belga com Morangos",
  "Ninho Trufado",
  "Oreo",
  "Prestígio",
  "Creme de Moça com Geleia de Morango",
  "doce de leite",
  "Chocolate Gourmet",
  "Bombom",
  "Ameixa",
  "Beijinho de Coco",
  "Musse de Morango",
  "Abacaxi"
 ]
};
